services:
  comfyui:
    image: mmartial/comfyui-nvidia-docker:ubuntu24_cuda12.8-latest
    container_name: comfyui
    ports:
      - "127.0.0.1:8188:8188"
    gpus: all
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    mem_limit: 16g
    cpus: "4.0"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - BASE_DIRECTORY=/basedir
      - WANTED_UID=1000
      - WANTED_GID=1000
      - COMFYUI_ARGS=--fast --use-pytorch-cross-attention
    volumes:
      - ./run:/comfy/mnt
      - ./basedir:/basedir
    restart: unless-stopped
    runtime: nvidia
